<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.5NDZMIG' shared service.

return $this->privates['.service_locator.5NDZMIG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\FicheFraisController::deleteVerif' => ['privates', '.service_locator.VpK.6BC', 'get_ServiceLocator_VpK_6BCService.php', true],
    'App\\Controller\\FicheFraisController::deleterArticle' => ['privates', '.service_locator.VpK.6BC', 'get_ServiceLocator_VpK_6BCService.php', true],
    'App\\Controller\\FicheFraisController::indexAction' => ['privates', '.service_locator.VpK.6BC', 'get_ServiceLocator_VpK_6BCService.php', true],
    'App\\Controller\\FicheFraisController::updateAction' => ['privates', '.service_locator.VpK.6BC', 'get_ServiceLocator_VpK_6BCService.php', true],
    'App\\Controller\\FicheFraisController:deleteVerif' => ['privates', '.service_locator.VpK.6BC', 'get_ServiceLocator_VpK_6BCService.php', true],
    'App\\Controller\\FicheFraisController:deleterArticle' => ['privates', '.service_locator.VpK.6BC', 'get_ServiceLocator_VpK_6BCService.php', true],
    'App\\Controller\\FicheFraisController:indexAction' => ['privates', '.service_locator.VpK.6BC', 'get_ServiceLocator_VpK_6BCService.php', true],
    'App\\Controller\\FicheFraisController:updateAction' => ['privates', '.service_locator.VpK.6BC', 'get_ServiceLocator_VpK_6BCService.php', true],
], [
    'App\\Controller\\FicheFraisController::deleteVerif' => '?',
    'App\\Controller\\FicheFraisController::deleterArticle' => '?',
    'App\\Controller\\FicheFraisController::indexAction' => '?',
    'App\\Controller\\FicheFraisController::updateAction' => '?',
    'App\\Controller\\FicheFraisController:deleteVerif' => '?',
    'App\\Controller\\FicheFraisController:deleterArticle' => '?',
    'App\\Controller\\FicheFraisController:indexAction' => '?',
    'App\\Controller\\FicheFraisController:updateAction' => '?',
]);
