<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.jz_7g.C' shared service.

return $this->privates['.service_locator.jz_7g.C'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\ComptableController::deleteVerif' => ['privates', '.service_locator.VpK.6BC', 'get_ServiceLocator_VpK_6BCService.php', true],
    'App\\Controller\\ComptableController::deleterArticle' => ['privates', '.service_locator.VpK.6BC', 'get_ServiceLocator_VpK_6BCService.php', true],
    'App\\Controller\\ComptableController::indexAction' => ['privates', '.service_locator.VpK.6BC', 'get_ServiceLocator_VpK_6BCService.php', true],
    'App\\Controller\\ComptableController::updateAction' => ['privates', '.service_locator.VpK.6BC', 'get_ServiceLocator_VpK_6BCService.php', true],
    'App\\Controller\\ComptableController:deleteVerif' => ['privates', '.service_locator.VpK.6BC', 'get_ServiceLocator_VpK_6BCService.php', true],
    'App\\Controller\\ComptableController:deleterArticle' => ['privates', '.service_locator.VpK.6BC', 'get_ServiceLocator_VpK_6BCService.php', true],
    'App\\Controller\\ComptableController:indexAction' => ['privates', '.service_locator.VpK.6BC', 'get_ServiceLocator_VpK_6BCService.php', true],
    'App\\Controller\\ComptableController:updateAction' => ['privates', '.service_locator.VpK.6BC', 'get_ServiceLocator_VpK_6BCService.php', true],
], [
    'App\\Controller\\ComptableController::deleteVerif' => '?',
    'App\\Controller\\ComptableController::deleterArticle' => '?',
    'App\\Controller\\ComptableController::indexAction' => '?',
    'App\\Controller\\ComptableController::updateAction' => '?',
    'App\\Controller\\ComptableController:deleteVerif' => '?',
    'App\\Controller\\ComptableController:deleterArticle' => '?',
    'App\\Controller\\ComptableController:indexAction' => '?',
    'App\\Controller\\ComptableController:updateAction' => '?',
]);
