<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIWTh5zG\srcApp_KernelDevContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIWTh5zG/srcApp_KernelDevContainer.php') {
    touch(__DIR__.'/ContainerIWTh5zG.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevContainer::class, false)) {
    \class_alias(\ContainerIWTh5zG\srcApp_KernelDevContainer::class, srcApp_KernelDevContainer::class, false);
}

return new \ContainerIWTh5zG\srcApp_KernelDevContainer([
    'container.build_hash' => 'IWTh5zG',
    'container.build_id' => '127cdcb9',
    'container.build_time' => 1571318323,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIWTh5zG');
