<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOBK1jNl\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOBK1jNl/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOBK1jNl.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOBK1jNl\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerOBK1jNl\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'OBK1jNl',
    'container.build_id' => '782d3ddc',
    'container.build_time' => 1574958536,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOBK1jNl');
