<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYdvHpGp\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYdvHpGp/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYdvHpGp.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYdvHpGp\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerYdvHpGp\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'YdvHpGp',
    'container.build_id' => '011d3534',
    'container.build_time' => 1573742731,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYdvHpGp');
