<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEwESn42\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEwESn42/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEwESn42.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEwESn42\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerEwESn42\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'EwESn42',
    'container.build_id' => '33b5c95f',
    'container.build_time' => 1584019896,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEwESn42');
